// vite-react/src/App.tsx
import { Suspense, lazy } from 'react';
import reactLogo from '@assets/react.svg';
import './App.css';
import Header from './components/Header/index';
import Home from './components/Home';
import { devDependencies } from '../package.json';
import Loading from './components/Loading';
const Event = lazy(() => import('./components/Event/index'));
function App() {
  console.log(devDependencies, 'devDependencies');
  return (
    <div className="App">
      <div>
        <a href="https://reactjs.org" target="_blank" rel="noreferrer">
          <img src={reactLogo} className="logo react w-40" alt="React logo" />
        </a>
      </div>
      <h2>version: {devDependencies.vite}</h2>
      <p className="bg-red-400">CPP Hello Vite + React!</p>
      <Header />
      <Suspense fallback={<Loading />}>
        <div className="cpp">
          <Event />
        </div>
      </Suspense>
      <Home />
    </div>
  );
}

export default App;

// vite-vue-remote/src/App.vue
<script setup lang="ts">
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://vuejs.org/api/sfc-script-setup.html#script-setup
import HelloWorld from "./components/HelloWorld.vue";
import ButtonCom from "./components/Button.vue";
import { getImageUrl } from "./utils/index";
import imgUrl from "./assets/vue.svg";
const vite = getImageUrl("/vite.svg");
console.log(imgUrl, vite);
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img :src="`${vite}`" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img
        :src="`${imgUrl}`"
        class="logo vue"
        alt="Vue
      logo"
      />
    </a>
  </div>
  <!-- <HelloWorld msg="Vite + Vue" /> -->
  <ButtonCom msg="远程应用 ：：cpp + btn" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
